use fftdb;
INSERT INTO Users (Name, Password) values ('anon', 'none');
INSERT INTO Users (Name, Password, Reputation) values ('jehrenho', 'fftrox', 6);
INSERT INTO Users (Name, Password, Reputation) values ('dwayne_johnson', 'yolo', 3);
INSERT INTO Users (Name, Password, Reputation) values ('jackMan3', '1234', 3);
INSERT INTO Users (Name, Password) values ('jill', '4321');
INSERT INTO Posts (AuthorID, Body) values (2, 'I should probably eat something but this server ain\'t gonna build itself');
INSERT INTO PostsByUser (UserID, PostID) values (2, 4);
INSERT INTO Posts (AuthorID, Body) values (4, 'I love this app, fft has taught me so much about my own eating habits it\'s crazy');
INSERT INTO PostsByUser (UserID, PostID) values (1, 3);
INSERT INTO Posts (AuthorID, Body) values (3, 'Can you smell what the rock is cooking!?! Answer: Pan seared cod with a lemon dill sauce');
INSERT INTO PostsByUser (UserID, PostID) values (3, 2);
INSERT INTO Posts (AuthorID, Body) values (2, 'I love blackberry season! I pass by blackberry vines everyday to get to my bus stop. They make a quick and easy snack!');
INSERT INTO PostsByUser (UserID, PostID) values (2, 1);
